name: Sync to GitLab and Bitbucket

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to GitLab
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.GITLAB_TOKEN }}
        with:
          source-directory: '.'
          destination-github-username: 'arthurdessauxumlp'
          destination-repository-name: 'SAE1_sandfall_interactive'
          user-email: 'arthurdessauxumlp@gmail.com'
          target-branch: 'main'

      - name: Push to Bitbucket
        uses: test-room-7/action-update-repo@v1
        with:
          token: "${{ secrets.BITBUCKET_TOKEN }}"
          source-repo-url: "https://github.com/arthurdessauxumlp/SAE1_sandfall_interactive.git"
          destination-repo-url: "https://x-token-auth:${{ secrets.BITBUCKET_TOKEN }}@bitbucket.org/arthurdessauxumlp/sae1_sandfall_interactive.git"
          branch: "main"
